"""SQLAlchemy database models for reports and report events.

Implements data models as specified in DESIGN.md section 3.1.
"""

from __future__ import annotations

from typing import Any
from sqlalchemy import Float, ForeignKey, JSON, String, Text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship


class Base(DeclarativeBase):
    """Base declarative class for SQLAlchemy models."""

    pass


class Report(Base):
    """Central store for infrastructure issue reports.

    Corresponds to the `reports` table in DESIGN section 3.1.
    """

    __tablename__ = "reports"

    # UUID primary key generated on device, acting as idempotency key (FR-SYN-5)
    id: Mapped[str] = mapped_column(String, primary_key=True)
    category: Mapped[str] = mapped_column(String, nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    location_text: Mapped[str] = mapped_column(String(200), nullable=False)
    latitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    longitude: Mapped[float | None] = mapped_column(Float, nullable=True)
    priority: Mapped[str] = mapped_column(String, nullable=False)
    status: Mapped[str] = mapped_column(String, nullable=False)
    reporter_name: Mapped[str | None] = mapped_column(String, nullable=True)
    reported_at: Mapped[str] = mapped_column(String, nullable=False)
    received_at: Mapped[str] = mapped_column(String, nullable=False)
    updated_at: Mapped[str] = mapped_column(String, nullable=False)

    # Append-only events associated with this report
    events: Mapped[list[ReportEvent]] = relationship(
        "ReportEvent",
        back_populates="report",
        cascade="all, delete-orphan",
        order_by="ReportEvent.occurred_at",
    )


class ReportEvent(Base):
    """Append-only audit history events for reports.

    Corresponds to the `report_events` table in DESIGN section 3.1.
    """

    __tablename__ = "report_events"

    # UUID primary key generated by device or server
    id: Mapped[str] = mapped_column(String, primary_key=True)
    report_id: Mapped[str] = mapped_column(
        String, ForeignKey("reports.id", ondelete="CASCADE"), nullable=False
    )
    type: Mapped[str] = mapped_column(String, nullable=False)
    actor_role: Mapped[str] = mapped_column(String, nullable=False)
    occurred_at: Mapped[str] = mapped_column(String, nullable=False)
    recorded_at: Mapped[str] = mapped_column(String, nullable=False)
    details: Mapped[dict[str, Any] | None] = mapped_column(JSON, nullable=True)

    report: Mapped[Report] = relationship("Report", back_populates="events")
