"""Pydantic schemas and validation rules for the Offline Field Issue Tracker.

Implements requirements from SRS 3.1, 3.2 and DESIGN 3.1, 5, 7.
"""

from __future__ import annotations

from datetime import datetime, timedelta, timezone
from enum import Enum
from typing import Any

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    field_validator,
    model_validator,
    ValidationError,
)
from pydantic_core import InitErrorDetails, PydanticCustomError

from app.workflow import Status


class Category(str, Enum):
    """Permitted problem categories (SRS FR-CRT-2)."""

    WATER_POINT = "Water point"
    EQUIPMENT_DAMAGE = "Equipment damage"
    SERVICE_INTERRUPTION = "Service interruption"
    SAFETY_CONCERN = "Safety concern"
    MAINTENANCE = "Maintenance"


class Priority(str, Enum):
    """Permitted priority levels (SRS FR-CRT-3)."""

    LOW = "Low"
    MEDIUM = "Medium"
    HIGH = "High"
    CRITICAL = "Critical"


class EventType(str, Enum):
    """Permitted report audit event types (DESIGN 3.1)."""

    CREATED = "created"
    SUBMITTED = "submitted"
    SYNC_ATTEMPT_FAILED = "sync_attempt_failed"
    SYNCHRONIZED = "synchronized"
    STATUS_CHANGED = "status_changed"
    TRANSITION_REJECTED = "transition_rejected"


class ActorRole(str, Enum):
    """Roles recording audit events (DESIGN 3.1)."""

    FIELD_WORKER = "field_worker"
    COORDINATOR = "coordinator"
    SYSTEM = "system"


# Shared error response shape (DESIGN section 5)
class ErrorResponse(BaseModel):
    """Standard error response format across the entire API."""

    code: str
    message: str
    fields: dict[str, str] = Field(default_factory=dict)


class ClientEvent(BaseModel):
    """An event generated on the device delivered with a report (DESIGN 3.1, 3.2)."""

    id: str = Field(..., description="UUID primary key generated by device")
    type: str = Field(..., description="Event type")
    actor_role: str = Field(default="field_worker", description="Acting role")
    occurred_at: str | datetime = Field(..., description="Device timestamp")
    details: dict[str, Any] | None = None

    @field_validator("occurred_at")
    @classmethod
    def serialize_occurred_at(cls, v: str | datetime) -> str:
        if isinstance(v, datetime):
            return v.isoformat()
        return v


class ReportPutRequest(BaseModel):
    """Payload for PUT /reports/{id} idempotent delivery (DESIGN 3.1, 5, 7; SRS 3.2)."""

    id: str | None = Field(default=None, description="Report UUID (optional in body)")
    category: Category = Field(..., description="Problem category")
    description: str = Field(
        ...,
        min_length=10,
        max_length=1000,
        description="Detailed description (10-1000 characters, FR-VAL-2)",
    )
    location_text: str = Field(
        ...,
        min_length=1,
        max_length=200,
        description="Location description (max 200 characters, FR-VAL-2)",
    )
    latitude: float | None = Field(
        default=None,
        description="Latitude between -90 and 90 (FR-VAL-3)",
    )
    longitude: float | None = Field(
        default=None,
        description="Longitude between -180 and 180 (FR-VAL-3)",
    )
    priority: Priority = Field(..., description="Report priority (FR-CRT-3)")
    status: Status = Field(
        default=Status.SUBMITTED,
        description="Report status, must be 'Submitted' on delivery",
    )
    reporter_name: str | None = Field(
        default=None,
        description="Optional reporter name (FR-CRT-8)",
    )
    reported_at: datetime | str = Field(
        ...,
        description="Device timestamp, not in the future (FR-VAL-4)",
    )
    client_events: list[ClientEvent] = Field(
        default_factory=list,
        description="Undelivered client events delivered with report (FR-HIS-5)",
    )

    @field_validator("description")
    @classmethod
    def validate_description_content(cls, v: str) -> str:
        stripped = v.strip()
        if len(stripped) < 10:
            raise ValueError("Description must contain at least 10 non-whitespace characters.")
        if len(v) > 1000:
            raise ValueError("Description must not exceed 1000 characters.")
        return v

    @field_validator("location_text")
    @classmethod
    def validate_location_content(cls, v: str) -> str:
        stripped = v.strip()
        if not stripped:
            raise ValueError("Location text is required and cannot be empty.")
        if len(v) > 200:
            raise ValueError("Location text must not exceed 200 characters.")
        return stripped

    @field_validator("status")
    @classmethod
    def validate_submitted_status(cls, v: Status | str) -> Status:
        if isinstance(v, str):
            try:
                parsed = Status(v)
            except ValueError:
                raise ValueError(f"Status must be '{Status.SUBMITTED.value}'.")
        else:
            parsed = v

        if parsed != Status.SUBMITTED:
            raise ValueError(f"Status in delivery request must be '{Status.SUBMITTED.value}'.")
        return parsed

    @field_validator("latitude")
    @classmethod
    def validate_latitude_range(cls, v: float | None) -> float | None:
        if v is not None and not (-90.0 <= v <= 90.0):
            raise ValueError("Latitude must be between -90 and 90 degrees.")
        return v

    @field_validator("longitude")
    @classmethod
    def validate_longitude_range(cls, v: float | None) -> float | None:
        if v is not None and not (-180.0 <= v <= 180.0):
            raise ValueError("Longitude must be between -180 and 180 degrees.")
        return v

    @field_validator("reported_at")
    @classmethod
    def validate_reported_at(cls, v: datetime | str) -> str:
        if isinstance(v, str):
            try:
                # Handle ISO 8601 parsing with Z or offset
                normalized = v.replace("Z", "+00:00")
                dt = datetime.fromisoformat(normalized)
            except ValueError:
                raise ValueError("reported_at must be a valid ISO 8601 datetime string.")
        else:
            dt = v

        now = datetime.now(timezone.utc)
        if dt.tzinfo is None:
            # Assume UTC for naive timestamps
            dt = dt.replace(tzinfo=timezone.utc)

        # Allow 5 minutes clock tolerance for client clock skew
        max_allowed = now + timedelta(minutes=5)
        if dt > max_allowed:
            raise ValueError(
                "Date/time reported cannot be in the future (exceeds 5-minute tolerance)."
            )
        return dt.isoformat()

    @model_validator(mode="after")
    def validate_coordinate_pair(self) -> ReportPutRequest:
        """Coordinates must be given as both-or-neither (FR-VAL-3)."""
        errors: list[InitErrorDetails] = []

        if self.latitude is not None and self.longitude is None:
            errors.append(
                InitErrorDetails(
                    type=PydanticCustomError(
                        "missing_longitude",
                        "Longitude must be provided when latitude is given.",
                    ),
                    loc=("longitude",),
                    input=self.longitude,
                )
            )
        elif self.latitude is None and self.longitude is not None:
            errors.append(
                InitErrorDetails(
                    type=PydanticCustomError(
                        "missing_latitude",
                        "Latitude must be provided when longitude is given.",
                    ),
                    loc=("latitude",),
                    input=self.latitude,
                )
            )

        if errors:
            raise ValidationError.from_exception_data(self.__class__.__name__, errors)

        return self


# Alias for convenience
ReportCreate = ReportPutRequest


class ReportEventResponse(BaseModel):
    """Serialized audit event response (DESIGN 3.1)."""

    id: str
    report_id: str
    type: str
    actor_role: str
    occurred_at: str
    recorded_at: str
    details: dict[str, Any] | None = None

    model_config = ConfigDict(from_attributes=True)


class ReportResponse(BaseModel):
    """Serialized report response (DESIGN 3.1, 5)."""

    id: str
    category: str
    description: str
    location_text: str
    latitude: float | None = None
    longitude: float | None = None
    priority: str
    status: str
    reporter_name: str | None = None
    reported_at: str
    received_at: str
    updated_at: str

    model_config = ConfigDict(from_attributes=True)


class ReportDetailResponse(ReportResponse):
    """Report response including ordered history events (DESIGN 3.1, 5)."""

    events: list[ReportEventResponse] = Field(default_factory=list)


class TransitionRequest(BaseModel):
    """Payload for POST /reports/{id}/transition."""

    to: Status | str = Field(..., description="Target status")
    reason: str | None = Field(default=None, description="Optional or mandatory reason")
    expected_status: Status | str = Field(
        ..., description="Expected current status to detect concurrent updates"
    )


def format_validation_error_fields(
    errors: list[dict[str, Any]],
) -> dict[str, str]:
    """Extract a dictionary of {field_name: message} from Pydantic/FastAPI validation errors."""
    fields: dict[str, str] = {}
    for err in errors:
        loc = err.get("loc", ())
        # Filter out "body" from loc if present
        parts = [str(p) for p in loc if p != "body"]
        field_name = parts[-1] if parts else "__root__"

        msg = err.get("msg", "Invalid value")
        # Strip internal Pydantic prefix "Value error, " for cleaner messages
        if msg.startswith("Value error, "):
            msg = msg[len("Value error, "):]

        fields[field_name] = msg
    return fields
